force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoicess</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>test</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoicePDFController.cls
public class InvoicePDFController {

    public Id invoiceId { get; set; }
    public List<Invoice_Line__c> lines { get; set; }
    public Invoice__c invoiceHeader { get; set; }

    public InvoicePDFController() {
        invoiceId = ApexPages.currentPage().getParameters().get('id');


        if(invoiceId != null){

            invoiceHeader = [
                SELECT Id, Account__r.name, Opportunity__r.name,CreatedDate from Invoice__c where id = :invoiceId LIMIT 1
            ];
    
            lines = [
                SELECT Product__c, Product__r.Name, Quantity__c, Price__c, Total__c
                FROM Invoice_Line__c
                WHERE Invoice__c = :invoiceId
            ];
        }

    }

    public String getFormattedInvoiceNumber() {
    if (invoiceHeader == null || invoiceHeader.Id == null) {
        return '';
    }
    String idStr = String.valueOf(invoiceHeader.Id);
    // Get last 4 characters of Id
    String last4 = idStr.substring(idStr.length() - 4);

    // Format date (YYYYMMDD)
    String datePart = invoiceHeader.CreatedDate.format('yyyyMMdd');

    // Combine
    return 'INV-' + datePart + '-' + last4;
}
}